world:
- construction_cone_1
- construction_cone_2
- construction_cone_3
- construction_cone_4
- construction_cone_5
- construction_cone_6
- construction_cone_7
- construction_cone_8
- construction_cone_9
- construction_cone_10
- construction_cone_11
- construction_cone_12
- construction_cone_13
- construction_cone_14
- construction_cone_15
- construction_cone_16
- construction_cone_17
- construction_cone_18
- construction_cone_19
- construction_cone_20

